DiosBendiga/PlanB/Front/app.py
from flask import Flask

def create_app():
    app = Flask(__name__, instance_relative_config=False)
    with app.app_context():
        from routes.router import router
        app.register_blueprint(router)
    return app

DiosBendiga/PlanB/Front/routes/router.py
from flask import Flask, json, flash, Blueprint, url_for, jsonify, make_response, request, render_template, redirect, abort
import requests
import registrar_historial
import datetime
from urllib.parse import quote

router = Blueprint('router', __name__)



@router.route('/admin')
def admin():
    return render_template('fragmento/sintetica/lista.html')
@router.route('/grafo')
def grafo():
    return render_template("d3/grafo.html")

@router.route('/grafo/practica')
def grafo_practica():
    return render_template("d3/grafoDato.html")

@router.route('/admin/sintetica/list')
def list_sintetica():
    r = requests.get("http://localhost:8075/api/sintetica/list")
    data = r.json()
    return render_template('fragmento/sintetica/lista.html', list=data["data"])


@router.route('/admin/sintetica/edit/<int:id>')
def view_edit_sintetica(id):
    r = requests.get("http://localhost:8075/api/sintetica/list")
    data = r.json()
    r1 = requests.get(f"http://localhost:8075/api/sintetica/get/{id}")
    data1 = r1.json()
    
    if r1.status_code == 200:
        return render_template('fragmento/sintetica/editar.html', list=data["data"], sintetica=data1["data"])
    else:
        flash("sintetica no encontrado", category='error')
        return redirect("/admin/sintetica/list")


@router.route('/admin/sintetica/register')
def view_register_sintetica():
    r = requests.get("http://localhost:8075/api/sintetica/list")
    data = r.json()
    return render_template('fragmento/sintetica/registro.html', list=data["data"])

@router.route('/admin/sintetica/save', methods=["POST"])
def save_sintetica():
    headers = {'Content-type': 'application/json'}
    form = request.form

    # Debugging: Verifica si los datos están llegando correctamente
    print("Datos del formulario:", form)

    try:
        dataF = {
            "nombre": form["nombre"],
            "direccion": form["direccion"],
            "telefono": form["telefono"],
            "horario": form["horario"],
            "latitud": float(form["latitud"]),
            "longitud": float(form["longitud"]),
        }

        print("Datos enviados al backend:", dataF)  # Verifica los datos antes de enviarlos

        r = requests.post("http://localhost:8075/api/sintetica/save", data=json.dumps(dataF), headers=headers)
        dat = r.json()

        print("Respuesta de la API:", dat)  # Verifica la respuesta del backend

        if r.status_code == 200:
            flash("Sintética guardada correctamente", category='info')
            
        else:
            flash("Error al guardar la sintética", category='error')

    except ValueError:
        flash("Error: La latitud y longitud deben ser valores numéricos", category='error')

    return redirect(url_for("router.list_sintetica"))


@router.route('/admin/sintetica/delete/<int:id>', methods=['DELETE'])
def delete_sintetica(id):
    try:
        response = requests.delete(f"http://localhost:8075/api/sintetica/delete/{id}")
        if response.status_code == 200:
            flash("sintetica eliminado exitosamente", "info")
            registrar_historial("eliminar", "sintetica", f"sintetica con ID {id} eliminado")
            return jsonify({"message": "sintetica eliminado exitosamente."}), 200  # Responder con JSON
        else:
            flash("Error al eliminar el sintetica.", "danger")
            return jsonify({"error": "No se pudo eliminar el sintetica."}), response.status_code
    except Exception as e:
        flash(f"Hubo un error: {str(e)}", "danger")
        return jsonify({"error": str(e)}), 500  # Responder con JSON


@router.route('/admin/sintetica/update', methods=["POST"])
def update_sintetica():
    headers = {'Content-type': 'application/json'}
    form = request.form
    dataF = {
        "idSintetica": form["id"],
        "nombre": form["nombre"],
            "direccion": form["direccion"],
            "telefono": form["telefono"],
            "horario": form["horario"],
            "latitud": float(form["latitud"]),   # Corregido
            "longitud": float(form["longitud"]), 
    }
    r = requests.post("http://localhost:8075/api/sintetica/update", data=json.dumps(dataF), headers=headers)
    dat = r.json()
    
    if r.status_code == 200:
        flash("sintetica actualizado correctamente", category='info')
       
    else:
        flash(str(dat["data"]), category='error')

    return redirect("/admin/sintetica/list")

DiosBendiga/PlanB/Front/templates/d3/grafo.html
<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Visualización de Grafo</title>
    <link rel="stylesheet" href="https://unpkg.com/vis-network/styles/vis-network.css" />
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        #container {
            position: relative;
            padding: 20px;
        }

        #mynetwork {
            width: 100%;
            height: 80vh;
            border: 1px solid #ccc;
            background-color: #ffffff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .btn-back {
            position: absolute;
            top: 20px;
            left: 20px;
            padding: 10px 20px;
            background-color: #007bff;
            color: #ffffff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
            font-size: 16px;
        }

        .btn-back:hover {
            background-color: #0056b3;
        }

        p {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 20px;
            color: #333;
        }
    </style>
</head>
<body>
    <div id="container">
        <a href="javascript:history.back()" class="btn-back">Regresar</a>
        <p>GRAFO</p>
        <div id="mynetwork"></div>
    </div>

    <script src="https://unpkg.com/vis-network/standalone/umd/vis-network.min.js"></script>
    <script src="/static/d3/grafo.js"></script>
</body>
</html>

DiosBendiga/PlanB/Front/templates/d3/grafoDato.html
<!DOCTYPE html>
<html lang="en-US">
<head>
<script src="/static/d3/vis.js"></script>
<style type="text/css">
      #mynetwork {
        width: 600px;
        height: 400px;
        border: 1px solid lightgray;
      }
    </style>
</head>
<body>
<p>GRAFO.</p>

    <div id="mynetwork"></div>

    <script type="text/javascript" src="/static/d3/grafoDato.js">
      // create an array with nodes

    </script>
</body>
</html>

DiosBendiga/PlanB/Front/templates/fragmento/sintetica/distancia.html
{% extends "template.html" %}
{% block content %}

<!-- Formulario de búsqueda de recorrido -->
<div class="container mb-4">
    <form action="/sintetica/calcular_recorrido" method="POST">
        <div class="card mx-auto" style="max-width: 600px; padding: 20px;">
            <div class="card-body">
                <h5 class="card-title text-center mb-4">Buscar Distancia</h5>
                <div class="row">
                    <div class="col-lg-4 col-md-6 mb-3">
                        <label for="origen" class="form-label">Origen</label>
                        <select id="origen" name="origen" class="form-select">
                            {% for item in lista %}
                            <option value="{{ item.id }}">{{ item.nombre }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-lg-4 col-md-6 mb-3">
                        <label for="destino" class="form-label">Destino</label>
                        <select id="destino" name="destino" class="form-select">
                            {% for item in lista %}
                            <option value="{{ item.id }}">{{ item.nombre }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-lg-4 col-md-6 mb-3">
                        <label for="algoritmo" class="form-label">Algoritmo</label>
                        <select id="algoritmo" name="algoritmo" class="form-select">
                            <option value="1">Dijkstra</option>
                            <option value="2">Floyd-Warshall</option>
                        </select>
                    </div>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-danger">Buscar Distancia</button>
                </div>
            </div>
        </div>
    </form>
</div>

<!-- Sección del grafo -->
<h2 class="text-white text-center mb-4">Grafo de las Canchas</h2>
<div id="mynetwork" style="width: 100%; height: 400px; border: 1px solid lightgray; margin-bottom: 20px;"></div>

<!-- Scripts necesarios -->
<script src="/static/d3/vis.js"></script>
<script src="/static/d3/grafo.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
$(document).ready(function() {
    function updateOptions() {
        var selectedOrigin = $('#origen').val();
        var selectedDestination = $('#destino').val();
        $('#destino option').each(function() {
            $(this).toggle($(this).val() != selectedOrigin);
        });
        $('#origen option').each(function() {
            $(this).toggle($(this).val() != selectedDestination);
        });
    }
    $('#origen').change(updateOptions);
    $('#destino').change(updateOptions);
    updateOptions();

    // Mostrar alerta SweetAlert2 si hay mensajes
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                var decodedMessage = $("<textarea/>").html('{{ message }}').text();
                Swal.fire({
                    icon: '{{ category }}' == 'error' ? 'error' : 'success',
                    title: 'Información',
                    text: decodedMessage,
                    confirmButtonText: 'OK'
                });
            {% endfor %}
        {% endif %}
    {% endwith %}
});
</script>

{% endblock %}

DiosBendiga/PlanB/Front/templates/fragmento/sintetica/editar.html
{% extends 'index.html' %}

{% block content %}
<div class="container">
  <div class="pagetitle text-center">
    <h1 class="text-black">Editar sintetica </h1> <!-- Cambiado a text-black -->
  </div>
  
  <section class="section">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title text-white">Ingresa los datos del sintetica </h5>

            <form class="row g-3 needs-validation" method="POST" action="/admin/sintetica/update" novalidate>
                <input type="hidden" value="{{sintetica.idSintetica }}" name="id" />
                <div class="mb-3">
                  <label for="nombre" class="form-label text-white">Nombre del sintetica</label>
                  <input type="text" class="form-control" name="nombre" required value="{{ sintetica.nombre }}">
                </div>
                <div class="mb-3">
                  <label for="direccion" class="form-label text-white">Inversión sintetica</label>
                  <input type="text" class="form-control" name="direccion" required value="{{sintetica.direccion }}">
                </div>
                <div class="mb-3">
                  <label for="telefono" class="form-label text-white">Inversionistas</label>
                  <input type="number" class="form-control" name="telefono" required value="{{sintetica.telefono }}">
                </div>
                <div class="mb-3">
                  <label for="latitud" class="form-label text-white">Duracion sintetica</label>
                  <input type="Double" class="form-control" name="latitud" required value="{{ sintetica.latitud }}">
                </div>
                <div class="mb-3">
                  <label for="longitud" class="form-label text-white">Fecha de Inicio</label>
                  <input type="text" class="form-control" name="longitud" required value="{{ sintetica.longitud}}">
                </div>
                <div class="mb-3">
                  <label for="horario" class="form-label text-white">horario</label>
                  <input type="text" class="form-control" name="horario" required value="{{ sintetica.horario}}">
                </div>
         
                
                <a href="/admin/inversionista/list" class="btn btn-custom btn-secondary">Cancelar</a>
                <button type="submit" class="btn btn-custom btn-primary">Guardar</button> <!-- Estilo de botón personalizado -->
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

<style>
  .pagetitle {
    margin-bottom: 20px;
  }

  .text-black {
    color: #000; /* Color negro para el encabezado */
  }

  .text-white {
    color: #fff; /* Color blanco para otros textos */
  }

  .btn-custom {
    font-size: 14px;
    color: #fff;
    border-radius: 5px;
    padding: 8px 16px;
    transition: background-color 0.3s ease;
  }

  .btn-custom.btn-primary {
    background-color: #007bff; /* Color personalizado para el botón "Guardar" */
  }

  .btn-custom.btn-primary:hover {
    background-color: #0056b3; /* Color de fondo al pasar el mouse */
  }
</style>
<script>
  document.querySelectorAll('#star-rating .star').forEach(star => {
      star.addEventListener('click', function() {
          let value = this.getAttribute('data-value');
          let select = document.querySelector('#star-rating select');
          select.value = value;
          document.querySelectorAll('#star-rating .star').forEach(innerStar => {
              if (innerStar.getAttribute('data-value') <= value) {
                  innerStar.classList.add('selected');
              } else {
                  innerStar.classList.remove('selected');
              }
          });
      });
  });
</script>
<script>
  var map = L.map('map').setView([51.505, -0.09], 13);
  L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
  attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
  }).addTo(map);

  L.marker([51.5, -0.09]).addTo(map)
  .bindPopup('A pretty CSS popup.<br> Easily customizable.')
  .openPopup();
</script>

{% endblock %}

DiosBendiga/PlanB/Front/templates/fragmento/sintetica/grafo.html
{% extends "index.html" %}
{% block content %}
<h2 class="text-dark text-center mb-4">Matriz de Adyacencia</h2>

<div class="booking-form-body">
    <div class="row justify-content-center">
        <!-- Tarjeta estilizada para agregar adyacencia -->
        <div class="col-md-8 col-lg-6">
            <div class="card shadow-lg border-light">
                <div class="card-header bg-dark text-white text-center">
                    <h5 class="mb-0">Agregar Adyacencia</h5>
                </div>
                <div class="card-body">
                    <form id="form" action="{{ url_for('api.create_weights') }}" method="post" role="form">
                        <div class="row">
                            <div class="col-12 mb-3">
                                <label for="origen" class="form-label">Origen</label>
                                <select id="origen" name="origen" class="form-select">
                                    {% for item in lista %}
                                        <option value="{{ item.id }}">{{ item.nombre }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-12 mb-3">
                                <label for="destino" class="form-label">Destino</label>
                                <select id="destino" name="destino" class="form-select">
                                    {% for item in lista %}
                                        <option value="{{ item.id }}">{{ item.nombre }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-12 mb-3">
                                <button id="boton" type="submit" class="btn btn-primary w-100">Agregar</button>
                            </div>
                            <div class="col-12 mb-3">
                                <a href="/lista/sinteticas" class="btn btn-secondary w-100">VOLVER</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .card {
        border-radius: 10px;
        overflow: hidden;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    }

    .card-header {
        border-bottom: 1px solid #dee2e6;
        padding: 20px;
    }

    .card-body {
        padding: 20px;
    }

    .form-label {
        font-weight: bold;
    }

    .form-select {
        border-radius: 5px;
        border: 1px solid #ced4da;
        box-shadow: none;
        padding: 10px;
    }

    .btn {
        border-radius: 5px;
        padding: 10px;
    }

    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
        color: #fff;
    }

    .btn-primary:hover {
        background-color: #0056b3;
        border-color: #00408d;
    }

    .btn-secondary {
        background-color: #6c757d;
        border-color: #6c757d;
        color: #fff;
    }

    .btn-secondary:hover {
        background-color: #5a6268;
        border-color: #4e555b;
    }

    .table {
        width: 100%;
        border-collapse: collapse;
        background-color: #fff;
        color: #212529;
    }

    .table th, .table td {
        padding: 12px;
        text-align: center;
    }

    .table thead th {
        background-color: #f8f9fa;
        color: #343a40;
    }

    .table tbody td {
        background-color: #e9ecef;
        color: #343a40;
    }

    .table tbody tr:nth-of-type(odd) {
        background-color: #f1f3f5;
    }

    .text-center {
        text-align: center;
    }
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
$(document).ready(function() {
    function updateDestinationOptions() {
        var selectedOrigin = $('#origen').val();
        $('#destino option').each(function() {
            if ($(this).val() == selectedOrigin) {
                $(this).hide();
            } else {
                $(this).show();
            }
        });
    }

    function updateOriginOptions() {
        var selectedDestination = $('#destino').val();
        $('#origen option').each(function() {
            if ($(this).val() == selectedDestination) {
                $(this).hide();
            } else {
                $(this).show();
            }
        });
    }

    $('#origen').change(function() {
        updateDestinationOptions();
    });

    $('#destino').change(function() {
        updateOriginOptions();
    });

    updateDestinationOptions();
    updateOriginOptions();
});
</script>

<div class="scrollable-table">
    <table id="tabla" class="table text-dark mx-auto">
        <thead>
            <tr>
                <th>----</th>
                {% for item in lista %}
                    <th>{{ item.nombre }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for i in range(lista|length) %}
                <tr>
                    <td>{{ lista[i].nombre }}</td>
                    {% for j in range(lista|length) %}
                        <td>
                            {% if matriz[i][j] is not none %}
                                {{ matriz[i][j] }}
                            {% else %}
                                --
                            {% endif %}
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div style="text-align: center; margin-top: 20px;">
    <a href="/sintetica/camino" class="btn btn-secondary">Calcular el camino más corto</a>
</div>
{% endblock %}

DiosBendiga/PlanB/Front/templates/fragmento/sintetica/registro.html
{% extends 'index.html' %}

{% block content %}
<div class="container">
  <div class="pagetitle text-center">
    <h1 class="text-black">Registro de Proyectos</h1>
  </div>
  
  <section class="section">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title text-white">Ingresa los datos del sintetica</h5>

            <form class="row g-3 needs-validation" method="POST" action="{{ url_for('router.save_sintetica') }}" novalidate>

              <div class="mb-3">
                <label for="nombre" class="form-label text-black">Nombre</label>
                <input type="text" class="form-control" name="nombre" required>
              </div>
              <div class="mb-3">
                <label for="direccion" class="form-label text-black">Direccion</label>
                <input type="text" class="form-control" name="direccion" required>
              </div>
              <div class="mb-3">
                <label for="telefono" class="form-label text-black">Telefono</label>
                <input type="text" class="form-control" name="telefono" required>
              </div>
              <div class="mb-3">
                <label for="latitud" class="form-label text-black">Latitud</label>
                <input type="number" class="form-control" name="latitud" step="0.0000001" id="latitud" required>
              </div>
              <div class="mb-3">
                <label for="longitud" class="form-label text-black">Longitud</label>
                <input type="number" class="form-control" name="longitud" step="0.0000001" id="longitud" required>
              </div>
              
              <div class="mb-3">
                <label for="horario" class="form-label text-black">Horario</label>
                <input type="text" class="form-control" name="horario" required>
              </div>

              <!-- Contenedor del mapa -->
              <div class="map-container">
                <div id="map"></div>
              </div>

              <div class="d-flex justify-content-between mt-3">
                <button type="submit" class="btn btn-custom btn-light">Guardar</button>
                <a href="/admin/sintetica/list" class="btn btn-custom btn-secondary">Cancelar</a>
              </div>
            </form>

          </div>
        </div>
      </div>
    </div>
  </section>
</div>

<!-- Script para Leaflet -->
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
<script>
  document.querySelectorAll('#star-rating .star').forEach(star => {
      star.addEventListener('click', function() {
          let value = this.getAttribute('data-value');
          let select = document.querySelector('#star-rating select');
          select.value = value;
          document.querySelectorAll('#star-rating .star').forEach(innerStar => {
              if (innerStar.getAttribute('data-value') <= value) {
                  innerStar.classList.add('selected');
              } else {
                  innerStar.classList.remove('selected');
              }
          });
      });
  });
</script>


<script>
  var map = L.map("map", {
    center: [-1.8312, -78.1834], // Coordenadas de Ecuador
    zoom: 6,
    maxBounds: [[-5.0, -81.0], [2.5, -75.0]], // Limita el mapa a Ecuador
    maxBoundsViscosity: 1.0, // Mantiene el mapa dentro del área definida
    dragging: true,
    zoomControl: true,
    scrollWheelZoom: false, // Evita que se agrande con la rueda del mouse
  });

  L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png", {
    maxZoom: 18,
    minZoom: 6,
    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>',
  }).addTo(map);

  var marker;
  function onMapClick(e) {
    if (marker) {
      marker.setLatLng(e.latlng);
    } else {
      marker = L.marker(e.latlng).addTo(map);
    }

    var latitud = e.latlng.lat.toFixed(6);
    var longitud = e.latlng.lng.toFixed(6);

    document.getElementById('latitud').value = latitud;
    document.getElementById('longitud').value = longitud;
  }

  map.on('click', onMapClick);
</script>

<style>
  .pagetitle {
    margin-bottom: 20px;
  }

  .text-black {
    color: #000; /* Color negro para el encabezado y etiquetas */
  }

  .text-white {
    color: #fff; /* Color blanco para otros textos */
  }

  .btn-custom {
    font-size: 14px;
    color: #fff;
    border-radius: 5px;
    padding: 8px 16px;
    transition: background-color 0.3s ease;
  }

  .btn-custom.btn-light {
    background-color: #f8f9fa; /* Color claro para el botón "Guardar" */
    color: #000; /* Texto en negro */
  }

  .btn-custom.btn-secondary {
    background-color: #6c757d; /* Color gris para el botón "Cancelar" */
  }

  .btn-custom.btn-light:hover {
    background-color: #e2e6ea; /* Color de fondo al pasar el mouse */
  }

  .btn-custom.btn-secondary:hover {
    background-color: #5a6268; /* Color de fondo al pasar el mouse */
  }

  .map-container {
    width: 100%;
    display: flex;
    justify-content: center;
    margin-top: 10px;
  }

  #map {
    width: 200%;
    height: 300px; /* Tamaño pequeño del mapa */
    max-width: 500px; /* Controla el ancho del mapa */
    border: 1px solid #ccc;
    border-radius: 5px;
  }
</style>
{% endblock %}

DiosBendiga/PlanB/Front/templates/templateFirst.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Pages / Login - NiceAdmin Bootstrap Template</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{{ url_for('static', filename='assets/img/favicon.png') }}" rel="icon">
  <link href="{{ url_for('static', filename='assets/img/apple-touch-icon.png') }}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/boxicons/css/boxicons.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/quill/quill.snow.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/quill/quill.bubble.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/remixicon/remixicon.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/simple-datatables/style.css') }}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: NiceAdmin
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Updated: Apr 20 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <main>
    <div class="container">
      <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
          {% block content %}
          {% endblock %}
        </div>
      </section>
    </div>
  </main>

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{{ url_for('static', filename='vendor/apexcharts/apexcharts.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/chart.js/chart.umd.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/echarts/echarts.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/quill/quill.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/simple-datatables/simple-datatables.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/tinymce/tinymce.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/php-email-form/validate.js') }}"></script>

  <!-- Template Main JS File -->
  <script src="{{ url_for('static', filename='js/main.js') }}"></script>

</body>

</html>